#!/bin/bash
#arg 1 source file
export REAL=${1}_real.csv
export USER=${1}_user.csv

grep real $1 > real_tmp
sed -e 's/real/"real",/g' real_tmp > ${REAL}
printf "${1} Average real time: " >> ${1}.results
awk '{ sum += $2; n++ } END { if (n > 0) print sum / n; }' ${REAL} >> ${1}.results

grep user $1 > user_tmp
sed -e 's/user/"user",/g' user_tmp > ${USER}

printf "${1} Average user time: " >> ${1}.results
awk '{ sum += $2; n++ } END { if (n > 0) print sum / n; }' ${USER}  >> ${1}.results

rm $1
rm *_tmp
