#!/bin/bash

echo Transfer Cloud Compiler files to AWS image. 
echo Arg1: Pass the DNS of remote machine. Required.
echo Arg2: File argument. Required.

if [[ $# -eq 2 ]]; then
    export AWS=$1
    echo set AWS to $AWS
else
    echo Required args are 1: target dns, 2: file argument.
    exit 1
fi

read -p "Select credential: 1 for vpc-front, 2 for vpc-back, 3 for wind-be. " sel
case $sel in
  [1]* ) export CRED=~/.ssh/vpc-front.pem
        ;;
  [2]* ) export CRED=~/.ssh/vpc-back.pem 
        ;;
  [3]* ) export CRED=~/.ssh/wind-be.pem 
        ;;
  * ) echo "Invalid selection." 
      exit 1
        ;;
esac


echo
read -p "Transferring $2 to $1. Okay?" yn
case $yn in
        [Yy]* ) 
            scp -p -i ${CRED} $2  ops@${AWS}:$2
            ;;
        * ) echo "transfer skipped"
esac
