#!/bin/bash
cd notes
clc_get_file $CTL /home/ops/riemann/Notes_critical
clc_get_file $CTL /home/ops/riemann/Notes_influxdb
clc_get_file $CTL /home/ops/riemann/Notes_riemann
clc_get_file $CTL /home/ops/riemann/Notes_grafana
clc_get_file $CTL /home/ops/riemann/Notes_drip
cd ../riemann
clc_get_file $CTL /home/ops/riemann/etc/riemann.config
cd ../riemann-dash
clc_get_file $CTL /home/ops/riemann/riemann-dash/config.json
clc_get_file $CTL /home/ops/riemann/riemann-dash/dash.config
clc_get_file $CTL /home/ops/riemann/riemann-dash/README
cd ../influxdb
clc_get_file $CTL /home/ops/riemann/influxdb/clc_config.json
clc_get_file $CTL /home/ops/riemann/influxdb/influx_cmmd
cd ../upstart_control.amaret.com
clc_get_file $CTL /etc/init/riemann.conf
clc_get_file $CTL /etc/init/riemann-dash.conf
clc_get_file $CTL /etc/init/riemann-health.conf
